name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/facebookic.png
    - assets/page-1/images/left-side.png
    - assets/page-1/images/left-side-NFS.png
    - assets/page-1/images/left-side-KuA.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/auto-group-c1z8.png
    - assets/page-1/images/auto-group-pfe8.png
    - assets/page-1/images/wifi.png
    - assets/page-1/images/cib-apple.png
    - assets/page-1/images/back.png
    - assets/page-1/images/wifi-aWL.png
    - assets/page-1/images/googleic.png
    - assets/page-1/images/auto-group-br9s.png
    - assets/page-1/images/battery-fSx.png
    - assets/page-1/images/battery-6dN.png
    - assets/page-1/images/cib-apple-VLL.png
    - assets/page-1/images/facebookic-b4L.png
    - assets/page-1/images/vector-3.png
    - assets/page-1/images/battery-VS8.png
    - assets/page-1/images/auto-group-2nkp.png
    - assets/page-1/images/wifi-SEk.png
    - assets/page-1/images/back-33v.png
    - assets/page-1/images/vector-7.png
    - assets/page-1/images/vector-23.png
    - assets/page-1/images/icon-document.png
    - assets/page-1/images/googleic-3M2.png
    - assets/page-1/images/group-76.png
    - assets/page-1/images/vector-5.png
    - assets/page-1/images/vector-8.png
    - assets/page-1/images/maukuliah-1634870782-2.png
    - assets/page-1/images/left-side-jHJ.png
    - assets/page-1/images/vector-5-Ssr.png
    - assets/page-1/images/vector-7-QCx.png
    - assets/page-1/images/vector-2.png
    - assets/page-1/images/vector-8-5Di.png
    - assets/page-1/images/auto-group-gzat.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/battery-gZ6.png
    - assets/page-1/images/icon-arrow-down.png
    - assets/page-1/images/group-76-jJQ.png
    - assets/page-1/images/vector-14.png
    - assets/page-1/images/vector-2-p3J.png
    - assets/page-1/images/vector-17.png
    - assets/page-1/images/auto-group-o9e8.png
    - assets/page-1/images/battery-Zu2.png
    - assets/page-1/images/auto-group-1nq6.png
    - assets/page-1/images/vector-27.png
    - assets/page-1/images/wifi-NrU.png
    - assets/page-1/images/vector-18.png
    - assets/page-1/images/vector-13.png
    - assets/page-1/images/vector-29.png
    - assets/page-1/images/icon-document-s2Y.png
    - assets/page-1/images/icon-arrow-down-RZr.png
    - assets/page-1/images/iconly-bold-profile.png
    - assets/page-1/images/auto-group-hwds.png
    - assets/page-1/images/vector-32.png
    - assets/page-1/images/wifi-gWt.png
    - assets/page-1/images/vector-5-dS8.png
    - assets/page-1/images/vector-28.png
    - assets/page-1/images/group-1-3.png
    - assets/page-1/images/wifi-9vG.png
    - assets/page-1/images/wifi-nfa.png
    - assets/page-1/images/vector-34.png
    - assets/page-1/images/vector-9.png
    - assets/page-1/images/auto-group-qmep.png
    - assets/page-1/images/vector-22.png
    - assets/page-1/images/vector-7-c8p.png
    - assets/page-1/images/vector-2-mXW.png
    - assets/page-1/images/left-side-LKi.png
    - assets/page-1/images/vector-21.png
    - assets/page-1/images/auto-group-heic.png
    - assets/page-1/images/vector-24.png
    - assets/page-1/images/battery-vji.png
    - assets/page-1/images/vector-7-d1r.png
    - assets/page-1/images/vector-3-x48.png
    - assets/page-1/images/vector-ctg.png
    - assets/page-1/images/vector-6si.png
    - assets/page-1/images/auto-group-2lme.png
    - assets/page-1/images/vector-3-P84.png
    - assets/page-1/images/mobile-signal.png
    - assets/page-1/images/group-87.png
    - assets/page-1/images/iconly-light-arrow-right-6.png
    - assets/page-1/images/wifi-jh2.png
    - assets/page-1/images/vector-26.png
    - assets/page-1/images/auto-group-bsr2.png
    - assets/page-1/images/left-side-k1n.png
    - assets/page-1/images/vector-15.png
    - assets/page-1/images/group-50.png
    - assets/page-1/images/icon-arrow-left.png
    - assets/page-1/images/logo-png-1.png
    - assets/page-1/images/divregular-cross-small.png
    - assets/page-1/images/vector-33.png
    - assets/page-1/images/left-side-Rur.png
    - assets/page-1/images/vector-5-Lmv.png
    - assets/page-1/images/vector-35.png
    - assets/page-1/images/wifi-mip.png
    - assets/page-1/images/icon-arrow-down-x4Y.png
    - assets/page-1/images/vector-31.png
    - assets/page-1/images/vector-4.png
    - assets/page-1/images/vector-30.png
    - assets/page-1/images/left-side-QhE.png
    - assets/page-1/images/battery-Lqn.png
    - assets/page-1/images/vector-2-7be.png
    - assets/page-1/images/auto-group-mpst.png
    - assets/page-1/images/iconly-bold-logout.png
    - assets/page-1/images/auto-group-q4x8.png
    - assets/page-1/images/left-side-RPN.png
    - assets/page-1/images/icon-arrow-left-B7e.png
    - assets/page-1/images/vector-7-6v4.png
    - assets/page-1/images/auto-group-v5we.png
    - assets/page-1/images/group-1-4.png
    - assets/page-1/images/auto-group-erjx.png
    - assets/page-1/images/logo-png-1-c16.png
    - assets/page-1/images/auto-group-smdi.png
    - assets/page-1/images/wifi-ifi.png
    - assets/page-1/images/icon-arrow-left-TNQ.png
    - assets/page-1/images/battery-TwN.png
    - assets/page-1/images/iconly-light-arrow-right-2.png
    - assets/page-1/images/vector-16.png
    - assets/page-1/images/ellipse-bg.png
    - assets/page-1/images/battery-8YG.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
